format = """
[](#232634)\
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$time\
[ ](fg:#232634)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:#c6d0f5 bg:#232634"
style_root = "bg:#232634 fg:#e78284"
format = '[$user ]($style)'

[directory]
style = "fg:#c6d0f5 bg:#232634"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "fg:#e5c890 bg:#232634"
format = '[[ $symbol $branch ](fg:#e5c890 bg:#232634)]($style)'

[git_status]
style = "fg:#e5c890 bg:#232634"
format = '[[($all_status$ahead_behind )](fg:#e5c890 bg:#232634)]($style)'

[nodejs]
symbol = ""
style = "bg:#232634 fg:#85c1dc"
format = '[[ $symbol ($version) ](fg:#85c1dc bg:#232634)]($style)'

[rust]
symbol = ""
style = "bg:#232634 fg:#85c1dc"
format = '[[ $symbol ($version) ](fg:#85c1dc bg:#232634)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#232634 fg:#f4b8e4"
format = '[[ ♥ $time ](bg:#232634 fg:#e78284)]($style)'
